[project]
name = "langgraph-rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vaidehi2027", email = "vaidehimahale180@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.15.0",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.3.2",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.10",
    "python-dotenv>=1.2.2",
    "streamlit>=1.61.1",
]

[project.scripts]
langgraph-rag-project = "langgraph_rag_project:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
